package ch.ethz.syslab.telesto.protocol;

import java.nio.ByteBuffer;

/* 
 * Do not edit this file!
 * 
 * Edit the template at tools/protocol/telesto/templates/packet.java instead
 */
public class CreateQueuePacket extends Packet {
    public String name;

    public CreateQueuePacket() {
    }
    
    public CreateQueuePacket(int messageId, String name) {
        this.messageId = messageId;
        this.name = name;
    }

    @Override
    public byte methodId() {
        return 0x21;
    }

    @Override
    public void emit(ByteBuffer buffer) {
        int lengthIndex = buffer.position();
        buffer.position(lengthIndex + 2);
        buffer.put(methodId());
        buffer.putInt(messageId);
        putString(buffer, name);
        buffer.putShort(lengthIndex, (short) (buffer.position() - lengthIndex - 2));
    }

    @Override
    public void parse(ByteBuffer buffer) {
        messageId = buffer.getInt();
        name = getString(buffer);
    }

    @Override
    public CreateQueuePacket newInstance() {
        return new CreateQueuePacket();
    }
    
    public String toString() {
        return "CreateQueuePacket";
    }
}
