package ch.ethz.syslab.telesto.protocol;

import java.nio.ByteBuffer;

/* 
 * Do not edit this file!
 * 
 * Edit the template at tools/protocol/telesto/templates/packet.java instead
 */
public class ErrorPacket extends Packet {
    public byte errorCode;
    public String details;

    public ErrorPacket() {
    }
    
    public ErrorPacket(int messageId, byte errorCode, String details) {
        this.messageId = messageId;
        this.errorCode = errorCode;
        this.details = details;
    }

    @Override
    public byte methodId() {
        return 0x05;
    }

    @Override
    public void emit(ByteBuffer buffer) {
        int lengthIndex = buffer.position();
        buffer.position(lengthIndex + 2);
        buffer.put(methodId());
        buffer.putInt(messageId);
        buffer.put(errorCode);
        putString(buffer, details);
        buffer.putShort(lengthIndex, (short) (buffer.position() - lengthIndex - 2));
    }

    @Override
    public void parse(ByteBuffer buffer) {
        messageId = buffer.getInt();
        errorCode = buffer.get();
        details = getString(buffer);
    }

    @Override
    public ErrorPacket newInstance() {
        return new ErrorPacket();
    }
    
    public String toString() {
        return "ErrorPacket";
    }
}
