

package ch.ethz.syslab.telesto.protocol;

import java.nio.ByteBuffer;



/* 
 * Do not edit this file! 
 * 
 * Edit the template at tools/protocol/telesto/templates/packet.java instead.
 */
public class GetMessagesResponsePacket extends Packet {
    public Message[] messages;

    public GetMessagesResponsePacket() {
    }
    
    public GetMessagesResponsePacket(int packetId, Message[] messages) {
        this.packetId = packetId;
        this.messages = messages;
    }

    @Override
    public byte methodId() {
        return 46;
    }

    @Override
    public void emit(ByteBuffer buffer) {
        int lengthIndex = buffer.position();
        buffer.position(lengthIndex + 2);
        buffer.put(methodId());
        buffer.putInt(packetId);
        buffer.putInt(messages.length);
        for (int i = 0; i < messages.length; i++) {
            putMessage(buffer, messages[i]);
        }
        buffer.putShort(lengthIndex, (short) (buffer.position() - lengthIndex - 2));
    }

    @Override
    public void parse(ByteBuffer buffer) {
        packetId = buffer.getInt();
        messages = new Message[buffer.getInt()];
        for (int i = 0; i < messages.length; i++) {
            messages[i] = getMessage(buffer);
        }
    }

    @Override
    public GetMessagesResponsePacket newInstance() {
        return new GetMessagesResponsePacket();
    }
    
    public String toString() {
        return "GetMessagesResponsePacket";
    }
}