package ch.ethz.syslab.telesto.protocol;

import java.nio.ByteBuffer;

/* 
 * Do not edit this file!
 * 
 * Edit the template at tools/protocol/telesto/templates/packet.java instead
 */
public class GetMessagesResponsePacket extends Packet {

    public GetMessagesResponsePacket() {
    }
    
    public GetMessagesResponsePacket(int messageId) {
        this.messageId = messageId;
    }

    @Override
    public byte methodId() {
        return 0x2e;
    }

    @Override
    public void emit(ByteBuffer buffer) {
        int lengthIndex = buffer.position();
        buffer.position(lengthIndex + 2);
        buffer.put(methodId());
        buffer.putInt(messageId);
        buffer.putShort(lengthIndex, (short) (buffer.position() - lengthIndex - 2));
    }

    @Override
    public void parse(ByteBuffer buffer) {
        messageId = buffer.getInt();
    }

    @Override
    public GetMessagesResponsePacket newInstance() {
        return new GetMessagesResponsePacket();
    }
    
    public String toString() {
        return "GetMessagesResponsePacket";
    }
}
