

package ch.ethz.syslab.telesto.protocol;

import java.nio.ByteBuffer;

import ch.ethz.syslab.telesto.protocol.handler.PacketProcessingException;
import ch.ethz.syslab.telesto.protocol.handler.ProtocolHandler;



/* 
 * Do not edit this file! 
 * 
 * Edit the template at tools/protocol/telesto/templates/packet.java instead.
 */
public class GetQueueIdPacket extends Packet {
    public String name;

    public GetQueueIdPacket() {
    }

    public GetQueueIdPacket(String name) {
        this.name = name;
    }
    
    public GetQueueIdPacket(int packetId, String name) {
        this.packetId = packetId;
        this.name = name;
    }

    @Override
    public byte methodId() {
        return 37;
    }

    @Override
    public void emit(ByteBuffer buffer) {
        int lengthIndex = buffer.position();
        buffer.position(lengthIndex + 2);
        buffer.put(methodId());
        buffer.putInt(packetId);
        putString(buffer, name);
        buffer.putShort(lengthIndex, (short) (buffer.position() - lengthIndex - 2));
    }

    @Override
    public void parse(ByteBuffer buffer) {
        packetId = buffer.getInt();
        name = getString(buffer);
    }

    @Override
    public GetQueueIdPacket newInstance() {
        return new GetQueueIdPacket();
    }
    
    public Packet getHandled(ProtocolHandler handler) throws PacketProcessingException {
        return handler.handle((GetQueueIdPacket) this);
    }

    public String toString() {
        return "GetQueueIdPacket";
    }
}