

package ch.ethz.syslab.telesto.protocol;

import java.nio.ByteBuffer;

import ch.ethz.syslab.telesto.protocol.model.*;



/* 
 * Do not edit this file! 
 * 
 * Edit the template at tools/protocol/telesto/templates/packet.java instead.
 */
public class GetQueueNameResponsePacket extends Packet {
    public String name;

    public GetQueueNameResponsePacket() {
    }
    
    public GetQueueNameResponsePacket(int packetId, String name) {
        this.packetId = packetId;
        this.name = name;
    }

    @Override
    public byte methodId() {
        return 40;
    }

    @Override
    public void emit(ByteBuffer buffer) {
        int lengthIndex = buffer.position();
        buffer.position(lengthIndex + 2);
        buffer.put(methodId());
        buffer.putInt(packetId);
        putString(buffer, name);
        buffer.putShort(lengthIndex, (short) (buffer.position() - lengthIndex - 2));
    }

    @Override
    public void parse(ByteBuffer buffer) {
        packetId = buffer.getInt();
        name = getString(buffer);
    }

    @Override
    public GetQueueNameResponsePacket newInstance() {
        return new GetQueueNameResponsePacket();
    }
    
    public String toString() {
        return "GetQueueNameResponsePacket";
    }
}