

package ch.ethz.syslab.telesto.protocol;

import java.nio.ByteBuffer;



/* 
 * Do not edit this file! 
 * 
 * Edit the template at tools/protocol/telesto/templates/packet.java instead.
 */
public class IdentifyClientResponsePacket extends Packet {
    public byte mode;

    public IdentifyClientResponsePacket() {
    }

    public IdentifyClientResponsePacket(byte mode) {
        this.mode = mode;
    }
    
    public IdentifyClientResponsePacket(int packetId, byte mode) {
        this.packetId = packetId;
        this.mode = mode;
    }

    @Override
    public byte methodId() {
        return 20;
    }

    @Override
    public void emit(ByteBuffer buffer) {
        int lengthIndex = buffer.position();
        buffer.position(lengthIndex + 2);
        buffer.put(methodId());
        buffer.putInt(packetId);
        buffer.put(mode);
        buffer.putShort(lengthIndex, (short) (buffer.position() - lengthIndex - 2));
    }

    @Override
    public void parse(ByteBuffer buffer) {
        packetId = buffer.getInt();
        mode = buffer.get();
    }

    @Override
    public IdentifyClientResponsePacket newInstance() {
        return new IdentifyClientResponsePacket();
    }
    
    public String toString() {
        return "IdentifyClientResponsePacket";
    }
}