

package ch.ethz.syslab.telesto.protocol;

import java.nio.ByteBuffer;

import ch.ethz.syslab.telesto.model.Queue;


/* 
 * Do not edit this file! 
 * 
 * Edit the template at tools/protocol/telesto/templates/packet.java instead.
 */
public class QueueTestPacket extends Packet {
    public Queue queue;

    public QueueTestPacket() {
    }

    public QueueTestPacket(Queue queue) {
        this.queue = queue;
    }
    
    public QueueTestPacket(int packetId, Queue queue) {
        this.packetId = packetId;
        this.queue = queue;
    }

    @Override
    public byte methodId() {
        return 115;
    }

    @Override
    public void emit(ByteBuffer buffer) {
        int lengthIndex = buffer.position();
        buffer.position(lengthIndex + 2);
        buffer.put(methodId());
        buffer.putInt(packetId);
        putQueue(buffer, queue);
        buffer.putShort(lengthIndex, (short) (buffer.position() - lengthIndex - 2));
    }

    @Override
    public void parse(ByteBuffer buffer) {
        packetId = buffer.getInt();
        queue = getQueue(buffer);
    }

    @Override
    public QueueTestPacket newInstance() {
        return new QueueTestPacket();
    }
    
    public String toString() {
        return "QueueTestPacket";
    }
}