package ch.ethz.syslab.telesto.protocol;

import java.nio.ByteBuffer;

/* 
 * Do not edit this file!
 * 
 * Edit the template at tools/protocol/telesto/templates/packet.java instead
 */
public class ReadMessagePacket extends Packet {
    public int queueId;
    public int senderId;
    public byte mode;

    public ReadMessagePacket() {
    }
    
    public ReadMessagePacket(int messageId, int queueId, int senderId, byte mode) {
        this.messageId = messageId;
        this.queueId = queueId;
        this.senderId = senderId;
        this.mode = mode;
    }

    @Override
    public byte methodId() {
        return 0x33;
    }

    @Override
    public void emit(ByteBuffer buffer) {
        int lengthIndex = buffer.position();
        buffer.position(lengthIndex + 2);
        buffer.put(methodId());
        buffer.putInt(messageId);
        buffer.putInt(queueId);
        buffer.putInt(senderId);
        buffer.put(mode);
        buffer.putShort(lengthIndex, (short) (buffer.position() - lengthIndex - 2));
    }

    @Override
    public void parse(ByteBuffer buffer) {
        messageId = buffer.getInt();
        queueId = buffer.getInt();
        senderId = buffer.getInt();
        mode = buffer.get();
    }

    @Override
    public ReadMessagePacket newInstance() {
        return new ReadMessagePacket();
    }
    
    public String toString() {
        return "ReadMessagePacket";
    }
}
