package ch.ethz.syslab.telesto.protocol;

import java.nio.ByteBuffer;

/* 
 * Do not edit this file!
 * 
 * Edit the template at tools/protocol/telesto/templates/packet.java instead
 */
public class RegisterClientPacket extends Packet {
    public byte mode;

    public RegisterClientPacket() {
    }
    
    public RegisterClientPacket(int messageId, byte mode) {
        this.messageId = messageId;
        this.mode = mode;
    }

    @Override
    public byte methodId() {
        return 0x11;
    }

    @Override
    public void emit(ByteBuffer buffer) {
        int lengthIndex = buffer.position();
        buffer.position(lengthIndex + 2);
        buffer.put(methodId());
        buffer.putInt(messageId);
        buffer.put(mode);
        buffer.putShort(lengthIndex, (short) (buffer.position() - lengthIndex - 2));
    }

    @Override
    public void parse(ByteBuffer buffer) {
        messageId = buffer.getInt();
        mode = buffer.get();
    }

    @Override
    public RegisterClientPacket newInstance() {
        return new RegisterClientPacket();
    }
    
    public String toString() {
        return "RegisterClientPacket";
    }
}
