

package ch.ethz.syslab.telesto.protocol;

import java.nio.ByteBuffer;



/* 
 * Do not edit this file! 
 * 
 * Edit the template at tools/protocol/telesto/templates/packet.java instead.
 */
public class SuccessPacket extends Packet {

    public SuccessPacket() {
    }
    
    public SuccessPacket(int packetId) {
        this.packetId = packetId;
    }

    @Override
    public byte methodId() {
        return 3;
    }

    @Override
    public void emit(ByteBuffer buffer) {
        int lengthIndex = buffer.position();
        buffer.position(lengthIndex + 2);
        buffer.put(methodId());
        buffer.putInt(packetId);
        buffer.putShort(lengthIndex, (short) (buffer.position() - lengthIndex - 2));
    }

    @Override
    public void parse(ByteBuffer buffer) {
        packetId = buffer.getInt();
    }

    @Override
    public SuccessPacket newInstance() {
        return new SuccessPacket();
    }
    
    public String toString() {
        return "SuccessPacket";
    }
}