package ch.ethz.syslab.telesto.protocol.handler;

import ch.ethz.syslab.telesto.protocol.*;

/* 
 * Do not edit this file! 
 * 
 * Edit the template at tools/protocol/telesto/templates/handler.java instead.
 */
public interface IServerAuthenticationProtocolHandler {
   public abstract Packet handle(PingPacket packet) throws PacketProcessingException;
   public abstract Packet handle(RegisterClientPacket packet) throws PacketProcessingException;
   public abstract Packet handle(IdentifyClientPacket packet) throws PacketProcessingException;
}