package ch.ethz.syslab.telesto.common.protocol.handler;

import ch.ethz.syslab.telesto.common.protocol.*;

/* 
 * Do not edit this file! 
 * 
 * Edit the template at tools/protocol/telesto/templates/handler.java instead.
 */
public interface IServerProtocolHandler {
   public abstract Packet handle(PingPacket packet) throws PacketProcessingException;
   public abstract Packet handle(DeleteClientPacket packet) throws PacketProcessingException;
   public abstract Packet handle(CreateQueuePacket packet) throws PacketProcessingException;
   public abstract Packet handle(DeleteQueuePacket packet) throws PacketProcessingException;
   public abstract Packet handle(GetQueueIdPacket packet) throws PacketProcessingException;
   public abstract Packet handle(GetQueueNamePacket packet) throws PacketProcessingException;
   public abstract Packet handle(GetQueuesPacket packet) throws PacketProcessingException;
   public abstract Packet handle(GetActiveQueuesPacket packet) throws PacketProcessingException;
   public abstract Packet handle(GetMessagesPacket packet) throws PacketProcessingException;
   public abstract Packet handle(PutMessagePacket packet) throws PacketProcessingException;
   public abstract Packet handle(ReadMessagePacket packet) throws PacketProcessingException;
   public abstract Packet handle(ReadResponsePacket packet) throws PacketProcessingException;
   public abstract Packet handle(ComplexTestPacket packet) throws PacketProcessingException;
   public abstract Packet handle(MessageTestPacket packet) throws PacketProcessingException;
   public abstract Packet handle(QueueTestPacket packet) throws PacketProcessingException;
}