

package ch.ethz.syslab.telesto.common.protocol;

import java.nio.ByteBuffer;

import ch.ethz.syslab.telesto.common.protocol.handler.PacketProcessingException;
import ch.ethz.syslab.telesto.common.protocol.handler.ProtocolHandler;



/* 
 * Do not edit this file! 
 * 
 * Edit the template at tools/protocol/telesto/templates/packet.java instead.
 */
public class DeleteClientPacket extends Packet {

    public DeleteClientPacket() {
    }
    
    public DeleteClientPacket(int packetId) {
        this.packetId = packetId;
    }

    @Override
    public byte methodId() {
        return 21;
    }

    @Override
    public void emit(ByteBuffer buffer) {
        int lengthIndex = buffer.position();
        buffer.position(lengthIndex + 2);
        buffer.put(methodId());
        buffer.putInt(packetId);
        buffer.putShort(lengthIndex, (short) (buffer.position() - lengthIndex - 2));
    }

    @Override
    public void parse(ByteBuffer buffer) {
        packetId = buffer.getInt();
    }

    @Override
    public DeleteClientPacket newInstance() {
        return new DeleteClientPacket();
    }
    
    public Packet getHandled(ProtocolHandler handler) throws PacketProcessingException {
        return handler.handle((DeleteClientPacket) this);
    }

    public String toString() {
        return "DeleteClientPacket";
    }
}