package ch.ethz.syslab.telesto.server.controller;

import ch.ethz.syslab.telesto.protocol.*;

/* 
 * Do not edit this file! 
 * 
 * Edit the template at tools/protocol/telesto/templates/handler.java instead.
 */
public interface IPacketHandler {
   public abstract Packet handle(Packet packet) throws PacketProcessingException;
   public abstract Packet handle(PingPacket packet) throws PacketProcessingException;
   public abstract Packet handle(RegisterClientPacket packet) throws PacketProcessingException;
   public abstract Packet handle(IdentifyClientPacket packet) throws PacketProcessingException;
   public abstract Packet handle(CreateQueuePacket packet) throws PacketProcessingException;
   public abstract Packet handle(DeleteQueuePacket packet) throws PacketProcessingException;
   public abstract Packet handle(GetQueueIdPacket packet) throws PacketProcessingException;
   public abstract Packet handle(GetQueueNamePacket packet) throws PacketProcessingException;
   public abstract Packet handle(GetQueuesPacket packet) throws PacketProcessingException;
   public abstract Packet handle(GetActiveQueuesPacket packet) throws PacketProcessingException;
   public abstract Packet handle(GetMessagesPacket packet) throws PacketProcessingException;
   public abstract Packet handle(PutMessagePacket packet) throws PacketProcessingException;
   public abstract Packet handle(ReadMessagePacket packet) throws PacketProcessingException;
   public abstract Packet handle(ComplexTestPacket packet) throws PacketProcessingException;
   public abstract Packet handle(MessageTestPacket packet) throws PacketProcessingException;
   public abstract Packet handle(QueueTestPacket packet) throws PacketProcessingException;
}