package ch.ethz.syslab.telesto.common.util;

public enum ErrorType {
    INTERNAL_ERROR,
    UNEXPECTED_PACKET,
    IO_ERROR,
    UNIQUE_CONSTRAINT,
    QUEUE_NAME_NOT_UNIQUE,
    CLIENT_NOT_EXISTING,
    CLIENT_NAME_NOT_UNIQUE,
    QUEUE_NOT_EXISTING,
    NO_ACTIVE_QUEUES_EXISTING,
    NO_QUEUES_EXISTING,
    NO_MESSAGES_IN_QUEUE,
    NO_MESSAGES_RETRIEVED,
    REQUIRED_PARAMETER_MISSING,
    CLIENT_MODE_PERMISSION_VIOLATION;
}
